cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

django_ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
	url(r'^create/$', views.order_create, name='order_create')
]

shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from shop.models import Product


class Order(models.Model):
	first_name = models.CharField(max_length=60)
	last_name = models.CharField(max_length=60)
	email = models.EmailField()
	address = models.CharField(max_length=150)
	postal_code = models.CharField(max_length=30)
	city = models.CharField(max_length=100)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	paid = models.BooleanField(default=False)

	class Meta:
		ordering = ('-created', )

	def __str__(self):
		return 'Order {}'.format(self.id)

	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
	order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
	product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(default=1)

	def __str__(self):
		return '{}'.format(self.id)

	def get_cost(self):
		return self.price * self.quantity

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
    	ordering = ('name', )
    	verbose_name = 'category'
    	verbose_name_plural = 'categories'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    
    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
	return redirect('cart:cart_detail')


def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')


def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
	return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
	cart = Cart(request)
	if request.method == 'POST':
		form = OrderCreateForm(request.POST)
		if form.is_valid():
			order = form.save()
			for item in cart:
				OrderItem.objects.create(
					order=order,
					product=item['product'],
					price=item['price'],
					quantity=item['quantity']
				)
			cart.clear()
		return render(request, 'orders/order/created.html', {'order': order})
	else:
		form = OrderCreateForm()
	return render(request, 'orders/order/create.html', {'form': form})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = Product.objects.filter(category=category)

	context = {
		'category': category,
		'categories': categories,
		'products': products
	}
	return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
	product = get_object_or_404(Product, id=id, slug=slug, available=True)
	cart_product_form = CartAddProductForm()
	context = {
		'product': product,
		'cart_product_form': cart_product_form
	}
	return render(request, 'shop/product/detail.html', context)

cart/templates/cart/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
                            {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get__absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td>kshs. {{ item.price }}</td>
                            <td>kshs. {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>kshs. {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "shop:product_list" %}" class="btn btn-default">Continue Shopping</a>
            <a href="{% url "orders:order_create" %}" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order/create.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8">
                <h4 class="page-header">Checkout</h4>
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}<br>
                    <input type="submit" class="btn btn-primary" value="Submit order">
                </form>
            </div>
            <div class="col-md-4">
                <div class="page-header">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }}x {{ item.product.name }}
                        <span>Kshs. {{ item.total_price }}</span>
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Total Cost: kshs. {{ cart.get_total_price }}</li>
                </ul>

            </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order/created.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Thank you
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8 col-md-offset-2">
                <h3 class="page-header">Thank You For Shopping With Us
                </h3>
                <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
            </div>
        </div>
    </div>
{% endblock %}

shop/templates/shop/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}On-line Shop{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
	{% include 'shop/navbar.html' %}

	<div class="container">
		<div class="row" style="margin-top: 6%">
			 <button class="btn btn-info pull-right">
				{% with totail_items=cart|length %}
					{% if cart|length > 0 %}
						My Shopping Order:
						<a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
							{{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
						</a>
						{% else %}
						Your cart is empty.
					{% endif %}
				{% endwith %}
			 </button>
		</div>
	</div>
	{% block content %}
	
	
	{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

shop/templates/shop/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: #5AC8FA;">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container-fluid">
  	<div class="navbar-header">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
  	<span class="sr-only">Toggle navigation</span>
  	<span class="icon-bar"></span>
  	<span class="icon-bar"></span>
  	<span class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="{% url 'shop:product_list' %}" style="color: #ffffff">Henrylab Network</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

	<ul class="nav navbar-nav navbar-right">
  	<li class="dropdown">
      	{% if request.user.is_authenticated %}
    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>
    	<ul class="dropdown-menu">
      	<li><a href="">logout</a></li>
        	{% else %}
      	<li class="divider"></li>
      	<li><a href="#" style="color: #ffffff">Sign in</a></li>
     	<li><a href="#" style="color: #ffffff">Sign up</a></li>
    	</ul>
     	{% endif %}
  	</li>
	</ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

shop/templates/shop/product/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                <div class="card">
                    <div class="card-body">
                        <div class="col-md-6 text-right">
                            <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 170px; width: auto">
                        </div>
                        <div class="col-md-6" style="padding-left: 20px">
                            <h3>{{ product.name }}</h3>
                            <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
                            <p class="text-muted">Kshs. {{ product.price }}</p>
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_product_form }}
                                <input type="submit" value="add to cart" class="btn btn-primary">
                            </form>
                            <p>{{ product.description|safe|linebreaksbr }}</p>
                        </div>
                    </div>
                </div>
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->
      </div><!-- /.row -->

    </div><!-- /.container -->
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
	{% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container-fluid">
  	<div class="row" style="margin-top: 6%">

    	<div class="col-sm-8 blog-main">

      	<div class="blog-post">
          	<div class="row">
              	{% for product in products %}
                  	<div class="col-md-4">
                    	<div class="thumbnail">
                        	<a href="{{ product.get_absolute_url }}">
                            	<img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                        	</a>
                        	<div class="caption">
                            	<h3 class="text-center">
                                	<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            	</h3>
                            	<p class="text-center">Kshs. {{ product.price }}</p>
                        	</div>
                    	</div>
                  	</div>
              	{% endfor %}
          	</div>


      	</div><!-- /.blog-post -->

    	</div><!-- /.blog-main -->

    	<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
      	<div class="sidebar-module">
        	<h4>Categories</h4>
        	<ol class="list-unstyled">
          	<li {% if not category %} class="active"{% endif %}><a href="{% url 'shop:product_list' %}">All</a></li>
        	{% for c in categories %}

          	<li {% if category.slug == c.slug %} class="active"{% endif %}>
              	<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
          	</li>
        	{% endfor %}
        	</ol>
      	</div>
    	</div><!-- /.blog-sidebar -->

  	</div><!-- /.row -->

	</div><!-- /.container -->
{% endblock %}